POST http://0.0.0.0:8080/theme/themes
Accept: application/json
Content-Type: application/json

{
  "content": "history"
}

###

POST http://0.0.0.0:8080/theme/themes
Accept: application/json
Content-Type: application/json

{
  "content": "history",
  "parentThemeId": 1
}

###
@themeId = 1

GET http://0.0.0.0:8080/theme/detail/{{themeId}}?recreate=false
Accept: application/json
Content-Type: application/json

###
GET http://0.0.0.0:8080/theme/detail/{{themeId}}?recreate=true
Accept: application/json
Content-Type: application/json
X-Ai-Key: REPLACE_ME
X-Ai-Folder: REPLACE_ME
X-Ai-Provider: yandex
